### ISSUE TITLE
mybinder.org, colab, ... - would it be doable to execute something from Jupyter in the cloud?

### ISSUE THREAD

**Issue by slayoo** [atmos-cloud-sim-uj/PySDMachine.jl#1]

**Comment by slayoo** [comment]
Perhaps let's try this way:
- put the output netCDF files into the repo (what enables assertions if CI runs give the same results)
- put all plotting code in Jupyter notebook files
- add badges for Colab and mybinder, so it's easy to experiment with the data that is already in the repo (i.e., the "reference" output netcdf files)

Any thoughs?

**Comment by trontrytel** [comment]
I added the output files via this: https://git-lfs.github.com/

Lets see if that works!

**Comment by trontrytel** [comment]
I also added the Jupyter Lab notebook. Could you add Colab/binder? I have not done that before

**Comment by slayoo** [comment]
done!
